title: Rootinator
description: CTF Writeups & Bug Bounty Research
author: YuvalMil
email: your-email@example.com

# Build settings
theme: minima
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  writeups:
    output: true
    permalink: /writeups/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "YuvalMil"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "post"

# Navigation
header_pages:
  - writeups.md
  - about.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag